(() => {
  const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;let traveling=false;
  const css=[['wormhole-long','/wormhole-long.css'],['golden-constellation','/constellation.css'],['afterlight-portal','/afterlight-portal.css'],['supernova','/supernova.css'],['stilllight-portal','/stilllight-portal.css']];css.forEach(([key,href])=>{if(!document.querySelector(`link[data-${key}]`)){const s=document.createElement('link');s.rel='stylesheet';s.href=href;s.setAttribute(`data-${key}`,'true');document.head.appendChild(s);}});
  const portal=document.querySelector('.time-portal');
  /* Completed Afterlight and the two lights now forming Stilllight no longer sit in the present-day letter list. */
  const moved=new Set(['The Future I Had Already Met','The Space Between Our Words','If a Leaf Falls Quietly','Invisible :)','Three Dots','When I’m Ready','Always Here','Remember Me','The Goodbye You’ll Never Hear','When February Went Quiet']);
  document.querySelectorAll('.entries .entry').forEach(entry=>{const title=entry.querySelector('h2')?.textContent.trim();if(moved.has(title))entry.remove();});
  /* Golden remains free in the present universe even though it also has a fixed coordinate inside Afterlight. */
  if(portal&&!document.querySelector('.golden-star')){const g=document.createElement('a');g.className='golden-star';g.href='/constellations/golden/';g.setAttribute('aria-label','Golden — a wandering light');g.innerHTML='<span class="golden-star__meteor" aria-hidden="true"></span><span class="golden-star__label">Golden · still wandering</span>';document.body.appendChild(g);}
  if(portal&&!document.querySelector('.stilllight-distant')){const s=document.createElement('a');s.className='stilllight-distant';s.href='/constellations/stilllight/';s.setAttribute('aria-label','Stilllight — a constellation still forming');s.innerHTML='<span class="stilllight-copy"><strong>STILLLIGHT</strong><span>still forming · travel closer ↗</span></span><span class="stilllight-cluster" aria-hidden="true"><i class="s1"></i><i class="s2"></i><i class="s3"></i><span class="stilllight-trace"></span><span class="stilllight-mini-nova"></span><i class="f1"></i><i class="f2"></i><i class="f3"></i></span>';document.body.appendChild(s);s.addEventListener('click',e=>{if(reduceMotion)return;e.preventDefault();if(traveling)return;traveling=true;const r=s.getBoundingClientRect();document.documentElement.style.setProperty('--stilllight-x',`${r.left+r.width/2}px`);document.documentElement.style.setProperty('--stilllight-y',`${r.top+r.height/2}px`);const w=document.createElement('div');w.className='stilllight-warp';document.body.appendChild(w);setTimeout(()=>location.href=s.href,1800);});}
  if(portal&&!document.querySelector('.afterlight-galaxy')){const a=document.createElement('a');a.className='afterlight-galaxy';a.href='/constellations/afterlight/';a.setAttribute('aria-label','Afterlight — a completed distant constellation');a.innerHTML=`<span class="afterlight-galaxy__disc" aria-hidden="true"><svg viewBox="0 0 100 100"><path class="afterlight-mini__line" d="M38 88 L43 77 L44 64 L47 52 L47 41 L51 24 M38 88 L52 82 L54 67 L53 54 L51 43 L51 24 M47 41 L54 36 L51 24 M51 24 L40 31 L29 28 L20 35 M51 24 L60 19 L70 24 M76 28 L83 23 M51 24 L56 37 L55 50 L58 65 L65 75"/><circle class="afterlight-mini__star" cx="38" cy="88" r="1.5"/><circle class="afterlight-mini__star anchor secondary" cx="43" cy="77" r="1.5"/><circle class="afterlight-mini__star" cx="44" cy="64" r="1.4"/><circle class="afterlight-mini__star" cx="47" cy="52" r="1.4"/><circle class="afterlight-mini__star" cx="47" cy="41" r="1.3"/><circle class="afterlight-mini__star" cx="40" cy="31" r="1.3"/><circle class="afterlight-mini__star" cx="29" cy="28" r="1.3"/><circle class="afterlight-mini__star anchor" cx="51" cy="24" r="1.8"/><circle class="afterlight-mini__star" cx="58" cy="65" r="1.5"/><circle class="afterlight-mini__star anchor release" cx="65" cy="75" r="1.7"/></svg></span><span class="afterlight-galaxy__label">Afterlight · constellation</span>`;document.body.appendChild(a);a.addEventListener('click',e=>{if(reduceMotion)return;e.preventDefault();if(traveling)return;traveling=true;const r=a.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;document.documentElement.style.setProperty('--afterlight-x',`${x}px`);document.documentElement.style.setProperty('--afterlight-y',`${y}px`);const warp=document.createElement('div');warp.className='afterlight-warp';warp.innerHTML='<div class="afterlight-warp__stars"></div>';document.body.appendChild(warp);a.classList.add('is-traveling');document.body.classList.add('afterlight-traveling');setTimeout(()=>location.href=a.href,2350);});}
  function makeTransition(x,y,mode){document.documentElement.style.setProperty('--worm-x',`${x}px`);document.documentElement.style.setProperty('--worm-y',`${y}px`);const overlay=document.createElement('div');overlay.className=`wormhole-transition ${mode}`;overlay.innerHTML='<div class="space-veil"></div><div class="warp-stars"></div><div class="wormhole-glow"></div><div class="accretion-halo halo-back"></div><div class="event-horizon"></div><div class="accretion-halo halo-front"></div><div class="accretion-line"></div><div class="tunnel-depth"></div><div class="wormhole-flash"></div>';document.body.appendChild(overlay);requestAnimationFrame(()=>requestAnimationFrame(()=>document.body.classList.add('wormhole-traveling')));}
  function travel(link,x,y,mode,duration){if(traveling)return;traveling=true;makeTransition(x,y,mode);setTimeout(()=>location.href=link,duration);}
  if(portal)portal.addEventListener('click',e=>{if(reduceMotion)return;e.preventDefault();const r=portal.querySelector('.portal-orbit')?.getBoundingClientRect()||portal.getBoundingClientRect();portal.style.animationPlayState='paused';travel(portal.href,r.left+r.width/2,r.top+r.height/2,'to-past',2700);});
  const back=document.querySelector('.return-present');if(back)back.addEventListener('click',e=>{if(reduceMotion)return;e.preventDefault();const r=back.getBoundingClientRect();travel(back.href,r.left+r.width/2,r.top+r.height/2,'to-present',2250);});
})();